---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-intellij-community-opensuse
    image: opensuse/leap:15.2

provisioner:
  name: ansible

verifier:
  name: testinfra
