---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-intellij-community-opensuse
    image: opensuse/leap:15.2
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible

verifier:
  name: testinfra
