---
- name: create IntelliJ IDEA user config directory
  become: yes
  file:
    dest: '~{{ item.username }}/{{ intellij_user_dir }}/config'
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'ug=rwx,o=rx'
  with_items: '{{ users }}'

- name: configure disabled plugins
  become: yes
  template:
    src: disabled_plugins.txt.j2
    dest: '~{{ item.username }}/{{ intellij_user_dir }}/config/disabled_plugins.txt'
    force: no
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'ug=rw,o=r'
  with_items: '{{ users }}'
  when: "item.intellij_disabled_plugins is defined and item.intellij_disabled_plugins not in (None, '', omit)"
