# code: language=ansible
---
# Needed by custom Ansible modules
- name: Install Python XML support (Python 2)
  become: true
  ansible.builtin.package:
    name: python-lxml
    state: present
  when: "intellij_python_major_version == '2'"

- name: Install Python XML support (Python 3)
  become: true
  ansible.builtin.package:
    name: "python3-lxml"
    state: present
  when: "intellij_python_major_version == '3'"

- name: Configure license
  ansible.builtin.import_tasks: configure-license.yml

- name: Configure disabled plugins
  ansible.builtin.import_tasks: configure-disabled-plugins.yml

- name: Configure JDK table
  ansible.builtin.import_tasks: configure-jdk-table.yml

- name: Configure project defaults
  ansible.builtin.import_tasks: configure-project-defaults.yml

- name: Install code styles
  ansible.builtin.import_tasks: install-code-styles.yml

- name: Configure code style
  ansible.builtin.import_tasks: configure-code-style.yml

- name: Install inspection profiles
  ansible.builtin.import_tasks: install-inspection-profiles.yml

- name: Configure inspection profiles
  ansible.builtin.import_tasks: configure-inspection-profiles.yml

- name: Install plugins
  ansible.builtin.import_tasks: install-plugins.yml
