---
- include: configure-disabled-plugins.yml

- include: configure-jdk-table.yml

- include: configure-project-defaults.yml

- include: install-code-styles.yml

- include: configure-code-style.yml

- include: install-plugins.yml
  when: ansible_os_family == "Debian"
