---
- name: create IntelliJ IDEA user codestyles directory
  become: yes
  file:
    dest: '~{{ user.username }}/{{ intellij_user_config_dir }}/codestyles'
    state: directory
    owner: '{{ user.username }}'
    group: '{{ user.intellij_group | default(user.username) }}'
    mode: 'ug=rwx,o=rx'
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- name: download codestyles
  get_url:
    url: '{{ url }}'
    dest: "{{ intellij_download_dir }}/intellij-codestyle-{{ url | regex_replace('^.*/([^/]+).xml$', '\\1') }}-{{ url | hash('sha256') }}.xml"
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  loop: "{{ users | map(attribute='intellij_codestyles') | map('default', []) | flatten | map(attribute='url') | unique | list }}"
  loop_control:
    loop_var: url

- name: install codestyles
  become: yes
  copy:
    src: "{{ intellij_download_dir }}//intellij-codestyle-{{ item.1.url | regex_replace('^.*/([^/]+).xml$', '\\1') }}-{{ item.1.url | hash('sha256') }}.xml"
    remote_src: yes
    dest: '~{{ item.0.username }}/{{ intellij_user_config_dir }}/codestyles/{{ item.1.name }}.xml'
    force: yes
    owner: '{{ item.0.username }}'
    group: '{{ item.0.intellij_group | default(item.0.username) }}'
    mode: 'ug=rw,o=r'
  with_subelements:
    - '{{ users }}'
    - intellij_codestyles
    - skip_missing: yes
  loop_control:
    label: '{{ item.0.username }}: {{ item.1.name }}'
