---
- name: create IntelliJ IDEA user codestyles directory
  become: yes
  file:
    dest: '~{{ item.username }}/{{ intellij_user_dir }}/config/codestyles'
    state: directory
    owner: '{{ item.username }}'
    group: '{{ item.username }}'
    mode: 'ug=rwx,o=rx'
  with_items: '{{ users }}'

- name: download codestyles
  get_url:
    url: '{{ item.1.url }}'
    dest: "{{ intellij_download_dir }}/{{ item.1.url | regex_replace('^.*/([^/]+)$', '\\1') }}"
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  with_subelements:
    - '{{ users }}'
    - intellij_codestyles
    - skip_missing: yes

- name: install codestyles
  become: yes
  copy:
    src: "{{ intellij_download_dir }}/{{ item.1.url | regex_replace('^.*/([^/]+)$', '\\1') }}"
    remote_src: yes
    dest: '~{{ item.0.username }}/{{ intellij_user_dir }}/config/codestyles/{{ item.1.name }}.xml'
    force: no
    owner: '{{ item.0.username }}'
    group: '{{ item.0.username }}'
    mode: 'ug=rw,o=r'
  with_subelements:
    - '{{ users }}'
    - intellij_codestyles
    - skip_missing: yes
