---
# XMLStarlet is only avilable in the EPEL
- name: install epel-release (yum)
  become: yes
  yum:
    name: epel-release
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: install script dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - curl
    - dos2unix
    - findutils
    - gawk
    - grep
    - sed
    - unzip
    - xmlstarlet

- name: write plugin install script
  become: yes
  template:
    src: install-intellij-plugins.sh.j2
    dest: '{{ intellij_plugin_install_script }}'
    owner: root
    group: root
    mode: 'u=rwx,go='
  changed_when: no

# Workaround for: https://bugzilla.redhat.com/show_bug.cgi?id=1020147
- name: enable sudo tty workaround
  become: yes
  copy:
    content: "Defaults !requiretty\n"
    dest: '{{ intellij_sudo_tty_workaround }}'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  changed_when: no

- name: install plugins
  become: yes
  command: '{{ intellij_plugin_install_script }}'
  register: plugins_result
  changed_when: 'plugins_result.rc == 0'
  failed_when: 'plugins_result.rc >= 2'

- name: remove sudo tty workaround
  become: yes
  file:
    path: '{{ intellij_sudo_tty_workaround }}'
    state: absent
  changed_when: no
