---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-intellij-ultimate-ubuntu
    image: ubuntu:16.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: ultimate

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
