---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-intellij-ultimate-ubuntu
    image: ubuntu:18.04

provisioner:
  name: ansible
  config_options:
    defaults:
      inject_facts_as_vars: no

verifier:
  name: testinfra
  directory: ../default/tests
