---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-intellij-community-rocky
    image: rockylinux:9

provisioner:
  name: ansible

verifier:
  name: testinfra
