---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: "ansible_facts.pkg_mgr == 'apt'"

    - name: Create test users
      become: true
      ansible.builtin.user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: true
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install jdk 8
      become: true
      ansible.builtin.apt:
        name: openjdk-8-jdk-headless
        state: present

    - name: Install jdk 8 source
      become: true
      ansible.builtin.apt:
        name: openjdk-8-source
        state: present

    - name: Create java directory
      become: true
      ansible.builtin.file:
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
        dest: '/opt/java'

    - name: Download jdk 11
      ansible.builtin.get_url:
        url: 'https://api.adoptopenjdk.net/v3/binary/version/jdk-11.0.6%2B10/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk'
        dest: '/opt/java/jdk-11.0.6.tar.gz'
        force: false
        use_proxy: true
        validate_certs: true
        timeout: '{{ intellij_idea_download_timeout_seconds }}'
        mode: 'u=rw,go=r'

    - name: Install jdk 11
      become: true
      ansible.builtin.unarchive:
        src: '/opt/java/jdk-11.0.6.tar.gz'
        remote_src: true
        dest: '/opt/java'
        owner: root
        group: root
        mode: 'o-w'
        creates: '/opt/java/jdk-11.0.6+10/bin'

    - name: Set facts for openjdk locations
      ansible.builtin.set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
        jdk11_home: '/opt/java/jdk-11.0.6+10'

    - name: Create example files dir
      become: true
      ansible.builtin.file:
        path: /example
        state: directory
        mode: 'u=rwx,go=rx'

    - name: Copy example files to remote
      ansible.builtin.copy:
        src: '../remote-files/{{ item }}'
        dest: /example/
        mode: 'u=rw,go=r'
      loop:
        - Example-style2.xml
        - Example2.xml

  roles:
    - role: ansible-role-intellij
      intellij_default_maven_home: '/test/maven/home'
      intellij_edition: community
      users:
        - username: test_usr
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
            - name: '11'
              home: '{{ jdk11_home }}'
          intellij_default_jdk: '1.8'
          intellij_disabled_plugins:
            - org.jetbrains.plugins.gradle
          intellij_codestyles:
            - name: Example1
              src: Example-style1.xml
            - name: Example2
              src: /example/Example-style2.xml
              remote_src: true
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          intellij_inspection_profiles:
            - name: Example1
              src: Example1.xml
            - name: Example2
              src: /example/Example2.xml
              remote_src: true
            - name: GantSign
              url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
          intellij_default_inspection_profile: GantSign
          intellij_plugins:
            - google-java-format
            - MavenRunHelper
            - com.dubreuia
        - username: test_usr2
          intellij_disabled_plugins:
          intellij_plugins: []
        - username: test_usr3
