---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible-role-intellij-community-ubuntu
    image: ubuntu:24.04

provisioner:
  name: ansible

verifier:
  name: testinfra
