---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: install jdk 8
      become: yes
      apt:
        name: openjdk-8-jdk
        state: present

    - name: install jdk 8 source
      become: yes
      apt:
        name: openjdk-8-source
        state: present

    - name: create jdk 10 installation directory
      become: yes
      file:
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
        dest: '/opt/java/jdk-10'

    - name: download jdk 10
      get_url:
        url: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.1%2B10/OpenJDK10_x64_Linux_201807101745.tar.gz'
        dest: '/opt/java/jdk-10.tar.gz'
        force: no
        use_proxy: yes
        validate_certs: yes
        timeout: '{{ intellij_idea_download_timeout_seconds }}'
        mode: 'u=rw,go=r'

    - name: install jdk 10
      become: yes
      unarchive:
        src: '/opt/java/jdk-10.tar.gz'
        remote_src: yes
        dest: '/opt/java/jdk-10'
        owner: root
        group: root
        creates: '/opt/java/jdk-10/jdk-10.0.1+10/bin'

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
        jdk10_home: '/opt/java/jdk-10/jdk-10.0.1+10'

  roles:
    - role: ansible-role-intellij
      intellij_default_maven_home: '/test/maven/home'
      intellij_edition: community
      users:
        - username: test_usr
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
            - name: '10'
              home: '{{ jdk10_home }}'
          intellij_default_jdk: '1.8'
          intellij_disabled_plugins:
            - org.jetbrains.plugins.gradle
          intellij_codestyles:
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          intellij_inspection_profiles:
            - name: GantSign
              url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
          intellij_default_inspection_profile: GantSign
          intellij_plugins:
            - google-java-format
            - Lombook Plugin
            - com.dubreuia
        - username: test_usr2
          intellij_disabled_plugins:
          intellij_plugins: []
        - username: test_usr3
