---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: "ansible_pkg_mgr == 'apt'"

    - name: create test users
      become: yes
      user:
        name: test_usr
        state: present
        home: /home/test_usr
        createhome: yes

  roles:
    - role: ansible-role-intellij
      users:
        - username: test_usr
