---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: "ansible_facts.pkg_mgr == 'apt'"

    - name: Create test users
      become: true
      ansible.builtin.user:
        name: test_usr
        state: present
        home: /home/test_usr
        createhome: true

  roles:
    - role: ansible-role-intellij
      users:
        - username: test_usr
