---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: test_usr
        state: present
        home: /home/test_usr
        createhome: yes

  roles:
    - role: ansible-role-intellij
      intellij_default_maven_home: '/test/maven/home'
      users:
        - username: test_usr
